# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Ottu', :git => 'https://github.com/ottuco/ottu-ios-sdk.git', :tag => '1.0.70'
pod 'ApplePayButton', :git => '"https://github.com/Maninder1991/ApplePayButton.git', :tag => '1.0.0'
  # Pods for Example

end
